// src/entities/event/controlledEvents.ts
import type { EventCardData } from "@/entities/event/types";

export const controlledEventCards: EventCardData[] = [
  {
    id: "london-music-night",
    title: "London Music Night",
    city: "London",
    country: "United Kingdom",
    category: "Music",
    dateLabel: "21 July",
    venue: "River Hall",
    description: "An evening of indie performances near the Thames.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "from £24",
  },
  {
    id: "berlin-design-week",
    title: "Berlin Design Week",
    city: "Berlin",
    country: "Germany",
    category: "Design",
    dateLabel: "28 July",
    venue: "Mitte Studio",
    description: "A compact showcase of product, spatial and digital design.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "free entry",
  },
  {
    id: "new-york-rooftop-jazz",
    title: "New York Rooftop Jazz",
    city: "New York",
    country: "United States",
    category: "Music",
    dateLabel: "3 August",
    venue: "Skyline Loft",
    description: "Late-night jazz session with a clear view over the city.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "from $32",
  },
  {
    id: "london-family-workshop",
    title: "London Family Workshop",
    city: "London",
    country: "United Kingdom",
    category: "Family",
    dateLabel: "9 August",
    venue: "Greenwich Lab",
    description: "A hands-on weekend workshop for families and curious kids.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "£12",
  },
  {
    id: "berlin-food-market",
    title: "Berlin Food Market",
    city: "Berlin",
    country: "Germany",
    category: "Food",
    dateLabel: "14 August",
    venue: "Kreuzberg Yard",
    description: "Small producers, street food counters and local tastings.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "free entry",
  },
  {
    id: "new-york-digital-art-expo",
    title: "New York Digital Art Expo",
    city: "New York",
    country: "United States",
    category: "Art",
    dateLabel: "22 August",
    venue: "Hudson Gallery",
    description: "Digital installations, projection rooms and short artist talks.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "from $18",
  },
  {
    id: "london-summer-football",
    title: "London Summer Football",
    city: "London",
    country: "United Kingdom",
    category: "Sports",
    dateLabel: "26 August",
    venue: "East Park Arena",
    description: "A friendly evening match with local clubs and family stands.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "from £19",
  },
  {
    id: "berlin-theatre-weekend",
    title: "Berlin Theatre Weekend",
    city: "Berlin",
    country: "Germany",
    category: "Arts & Theatre",
    dateLabel: "31 August",
    venue: "Kulturhaus Mitte",
    description: "Short plays, artist talks and late performances across one weekend.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "from €21",
  },
  {
    id: "new-york-film-premiere",
    title: "New York Film Premiere",
    city: "New York",
    country: "United States",
    category: "Film",
    dateLabel: "5 September",
    venue: "Hudson Cinema",
    description: "An independent film premiere followed by a small director Q&A.",
    imageUrl: "/event-placeholder.svg",
    priceLabel: "from $16",
  },
];
