// src/entities/event/mockEvents.ts
import type { EventPreview, EventCardData } from "@/entities/event/types";

export const mockEvents: EventPreview[] = [
  {
    id: "london-design-walk",
    title: "Design Walk",
    city: "London",
    category: "Design",
    dateLabel: "12 June",
    description: "Короткий маршрут по городским выставкам и витринам.",
  },
  {
    id: "berlin-night-code",
    title: "Night Code Session",
    city: "Berlin",
    category: "Tech",
    dateLabel: "18 June",
    description: "Вечерняя встреча про интерфейсы, данные и быстрые прототипы.",
  },
  {
    id: "new-york-rooftop-jazz",
    title: "Rooftop Jazz",
    city: "New York",
    category: "Music",
    dateLabel: "24 June",
    description: "Небольшой концерт на крыше с видом на летний город.",
  },
  {
    id: "london-food-lab",
    title: "Food Lab",
    city: "London",
    category: "Food",
    dateLabel: "2 July",
    description: "Учебная дегустация и разговор о локальных городских сценах.",
  },
  {
    id: "berlin-gallery-start",
    title: "Gallery Start",
    city: "Berlin",
    category: "Art",
    dateLabel: "9 July",
    description: "Спокойный обзор новых пространств для будущей карты событий.",
  },
  {
    id: "new-york-product-meetup",
    title: "Product Meetup",
    city: "New York",
    category: "Tech",
    dateLabel: "15 July",
    description: "Мини-встреча о продуктовых решениях и пользовательских сценариях.",
  },
];

export const mockEventCards: EventCardData[] = [
  {
    id: "london-music-night",
    title: "London Music Night",
    city: "London",
    country: "United Kingdom",
    category: "Music",
    dateLabel: "21 July",
    venue: "River Hall",
    description: "An evening of indie performances near the Thames.",
    imageUrl: "eventmap-gradient-music",
    priceLabel: "from £24",
  },
  {
    id: "berlin-design-week",
    title: "Berlin Design Week",
    city: "Berlin",
    country: "Germany",
    category: "Design",
    dateLabel: "28 July",
    venue: "Mitte Studio",
    description: "A compact showcase of product, spatial and digital design.",
    imageUrl: "eventmap-gradient-design",
    priceLabel: "free entry",
  },
  {
    id: "new-york-rooftop-jazz-card",
    title: "New York Rooftop Jazz",
    city: "New York",
    country: "United States",
    category: "Music",
    dateLabel: "3 August",
    venue: "Skyline Loft",
    description: "Late-night jazz session with a clear view over the city.",
    imageUrl: "eventmap-gradient-jazz",
    priceLabel: "from $32",
  },
  {
    id: "london-family-workshop",
    title: "London Family Workshop",
    city: "London",
    country: "United Kingdom",
    category: "Family",
    dateLabel: "9 August",
    venue: "Greenwich Lab",
    description: "A hands-on weekend workshop for families and curious kids.",
    imageUrl: "eventmap-gradient-family",
    priceLabel: "£12",
  },
  {
    id: "berlin-food-market",
    title: "Berlin Food Market",
    city: "Berlin",
    country: "Germany",
    category: "Food",
    dateLabel: "14 August",
    venue: "Kreuzberg Yard",
    description: "Small producers, street food counters and local tastings.",
    imageUrl: "eventmap-gradient-food",
    priceLabel: "free entry",
  },
  {
    id: "new-york-digital-art-expo",
    title: "New York Digital Art Expo",
    city: "New York",
    country: "United States",
    category: "Art",
    dateLabel: "22 August",
    venue: "Hudson Gallery",
    description: "Digital installations, projection rooms and short artist talks.",
    imageUrl: "eventmap-gradient-art",
    priceLabel: "from $18",
  },
];
