// src/shared/lib/routes.ts
import type { Locale } from "@/shared/lib/locales";

export const routes = {
  home: (locale: Locale) => `/${locale}`,
  login: (locale: Locale) => `/${locale}/login`,
  authCallback: () => "/auth/callback",
  search: (locale: Locale) => `/${locale}/search`,
  favorites: (locale: Locale) => `/${locale}/favorites`,
  demo: (locale: Locale) => `/${locale}/demo`,
  demoRoutes: (locale: Locale) => `/${locale}/demo/routes`,
  demoLab1: (locale: Locale) => `/${locale}/demo/lab-1`,
  demoZod: (locale: Locale) => `/${locale}/demo/zod`,
  demoFallback: (locale: Locale) => `/${locale}/demo/fallback`,
  demoStaticParams: (locale: Locale) => `/${locale}/demo/static-params`,
  demoControlledSource: (locale: Locale) => `/${locale}/demo/controlled-source`,
  eventDetail: (locale: Locale, id: string) => `/${locale}/events/${id}`,
  demoCachePolicy: (locale: Locale) => `/${locale}/demo/cache-policy`,
  demoRenderingStrategy: (locale: Locale) => `/${locale}/demo/rendering-strategy`,
  demoLiveCache: (locale: Locale) => `/${locale}/demo/live-cache`,
  demoClientSearch: (locale: Locale) => `/${locale}/demo/client-search`,
  demoSearchSegments: (locale: Locale) => `/${locale}/demo/search-segments`,
  demoSearchNavigation: (locale: Locale) => `/${locale}/demo/search-navigation`,
  demoLiveSearchSource: (locale: Locale) => `/${locale}/demo/live-search-source`,
  demoSeoBaseline: (locale: Locale) => `/${locale}/demo/seo-baseline`,
  demoParallelRoutes: (locale: Locale) => `/${locale}/demo/parallel-routes`,
  demoParallelRoutesWithModal: (locale: Locale) => `/${locale}/demo/parallel-routes/with-modal`,
  demoModalVsFullPage: (locale: Locale) => `/${locale}/demo/modal-vs-full-page`,
  demoSuspenseStreaming: (locale: Locale) => `/${locale}/demo/suspense-streaming`,
  demoSupabaseArchitecture: (locale: Locale) => `/${locale}/demo/supabase-architecture`,
  demoSupabaseRls: (locale: Locale) => `/${locale}/demo/supabase-rls`,
  demoSupabaseAuth: (locale: Locale) => `/${locale}/demo/supabase-auth`,
  demoSupabaseCloudFavorites: (locale: Locale) => `/${locale}/demo/supabase-cloud-favorites`,
  demoFinalArchitecture: (locale: Locale) => `/${locale}/demo/final-architecture`,
} as const;
