// src/app/[locale]/demo/seo-baseline/page.tsx
import Link from "next/link";
import {
  buildSearchHref,
  type SearchFilters,
} from "@/entities/search/searchFilters";
import {
  getLocaleFromParams,
  type LocaleParams,
} from "@/shared/lib/localeParams";
import { routes } from "@/shared/lib/routes";

type SeoBaselinePageProps = {
  params: LocaleParams;
};

type CheckBlock = {
  title: string;
  description: string;
  checks: string[];
};

const musicFilters: Partial<SearchFilters> = { category: "music" };
const musicLondonFilters: Partial<SearchFilters> = {
  category: "music",
  city: "london",
};

export default async function SeoBaselinePage({
  params,
}: SeoBaselinePageProps) {
  const locale = await getLocaleFromParams(params);
  const homePath = routes.home(locale);
  const searchPath = routes.search(locale);
  const musicPath = buildSearchHref({ filters: musicFilters, locale });
  const musicLondonPath = buildSearchHref({
    filters: musicLondonFilters,
    locale,
  });
  const queryFallbackPath = `${searchPath}?category=music&city=london`;
  const queryPath = `${searchPath}?q=jazz`;
  const detailPath = routes.eventDetail(locale, "london-music-night");

  const checkBlocks: CheckBlock[] = [
    {
      title: "DevTools: title, description, canonical, hreflang",
      description:
        "Open the page source first, then compare the same tags in browser DevTools.",
      checks: [
        "Find the title generated by Metadata API.",
        "Find meta description in the server HTML.",
        "Find rel=canonical for the current URL.",
        "Find hreflang links for en and ru.",
      ],
    },
    {
      title: "View Source vs hydrated DOM",
      description:
        "View Source shows HTML returned by the server. Elements shows DOM after the browser and hydration have run.",
      checks: [
        "Use View Source for the first SEO baseline check.",
        "Use Elements to confirm the browser did not hide or replace important content.",
        "Compare page h1 with metadata title.",
      ],
    },
    {
      title: "Search landing page",
      description:
        "Search pages should have URL-specific metadata and a clean canonical URL.",
      checks: [
        `${musicPath}: title, description, canonical, hreflang en/ru.`,
        `${queryFallbackPath}: canonical should point to ${musicLondonPath}.`,
        `${queryPath}: q should stay in canonical.`,
        "Check h1, event list and pagination when pagination appears.",
      ],
    },
    {
      title: "Event detail page",
      description:
        "Event detail metadata should come from event data, not from generic page copy.",
      checks: [
        `${detailPath}: title from event data.`,
        "Description from event data.",
        "Open Graph image and Twitter card.",
        "Canonical and hreflang en/ru.",
      ],
    },
    {
      title: "Sitemap and robots",
      description:
        "Sitemap and robots are site-level SEO routes generated by MetadataRoute.",
      checks: [
        "/sitemap.xml contains /en, /ru and product search pages.",
        "/sitemap.xml contains /en/search/music, /en/search/sports, /en/search/arts and /en/search/film.",
        "/sitemap.xml contains /en/events/london-music-night.",
        "/sitemap.xml does not contain /en/demo.",
        "/robots.txt in dev mode contains Disallow: / and Sitemap: http://localhost:3000/sitemap.xml.",
        "SITE_ENV=production switches robots to Allow: /.",
      ],
    },
    {
      title: "Final checklist",
      description:
        "The module 5 baseline is complete when page-level metadata and site-level routes agree.",
      checks: [
        "Home, search and detail pages render server HTML.",
        "Title template adds EventMap where page metadata provides a title.",
        "Canonical points to the clean URL.",
        "hreflang links connect /en and /ru.",
        "Sitemap contains product URLs only.",
        "Robots policy matches the current environment.",
      ],
    },
  ];

  const links = [
    { href: homePath, label: homePath },
    { href: searchPath, label: searchPath },
    { href: musicPath, label: musicPath },
    { href: queryFallbackPath, label: queryFallbackPath },
    { href: queryPath, label: queryPath },
    { href: detailPath, label: detailPath },
    { href: "/sitemap.xml", label: "/sitemap.xml" },
    { href: "/robots.txt", label: "/robots.txt" },
  ];

  return (
    <section className="container demo-page">
      <div className="demo-hero">
        <p className="hero__eyebrow">SEO Lab</p>
        <h1>SEO Lab: baseline check</h1>
        <p>
          Check the metadata, canonical links, hreflang links, sitemap and
          robots routes produced by EventMap.
        </p>
        <Link className="button button--secondary" href={routes.demo(locale)}>
          Back to Demo Lab
        </Link>
      </div>

      <div className="app-surface app-stack app-muted-copy">
        <h2>URLs to open</h2>
        <div className="app-cluster">
          {links.map((link) => (
            <Link className="app-chip" href={link.href} key={link.href}>
              {link.label}
            </Link>
          ))}
        </div>
      </div>

      <div className="app-grid">
        {checkBlocks.map((block) => (
          <article
            className="app-surface app-stack app-muted-copy"
            key={block.title}
          >
            <span className="app-badge">check</span>
            <h2>{block.title}</h2>
            <p>{block.description}</p>
            <ul>
              {block.checks.map((check) => (
                <li key={check}>{check}</li>
              ))}
            </ul>
          </article>
        ))}
      </div>
    </section>
  );
}
