// src/entities/routeMap/routes.ts
export type RouteMapItem = {
  dynamicSegments: string[];
  example: string;
  id: string;
  layer: "app" | "content" | "demo" | "api";
  pattern: string;
};

export const routeMapItems: RouteMapItem[] = [
  {
    id: "home-locale",
    pattern: "/[locale]",
    example: "/en",
    dynamicSegments: ["locale"],
    layer: "app",
  },
  {
    id: "event-detail",
    pattern: "/[locale]/events/[id]",
    example: "/en/events/london-music-night",
    dynamicSegments: ["locale", "id"],
    layer: "content",
  },
  {
    id: "demo-index",
    pattern: "/[locale]/demo",
    example: "/en/demo",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-route-map",
    pattern: "/[locale]/demo/routes",
    example: "/en/demo/routes",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-lab-1",
    pattern: "/[locale]/demo/lab-1?city=london",
    example: "/en/demo/lab-1?city=london",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-zod",
    pattern: "/[locale]/demo/zod",
    example: "/en/demo/zod",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-fallback",
    pattern: "/[locale]/demo/fallback?mode=empty",
    example: "/en/demo/fallback?mode=empty",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "search",
    pattern: "/[locale]/search",
    example: "/en/search",
    dynamicSegments: ["locale"],
    layer: "app",
  },
  {
    id: "favorites",
    pattern: "/[locale]/favorites",
    example: "/en/favorites",
    dynamicSegments: ["locale"],
    layer: "app",
  },
  {
    id: "demo-controlled-source",
    pattern: "/[locale]/demo/controlled-source",
    example: "/en/demo/controlled-source",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-cache-policy",
    pattern: "/[locale]/demo/cache-policy",
    example: "/en/demo/cache-policy",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-rendering-strategy",
    pattern: "/[locale]/demo/rendering-strategy",
    example: "/en/demo/rendering-strategy",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-live-cache",
    pattern: "/[locale]/demo/live-cache",
    example: "/en/demo/live-cache",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-client-search",
    pattern: "/[locale]/demo/client-search",
    example: "/en/demo/client-search",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-search-segments",
    pattern: "/[locale]/demo/search-segments",
    example: "/en/demo/search-segments",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-search-navigation",
    pattern: "/[locale]/demo/search-navigation",
    example: "/en/demo/search-navigation",
    dynamicSegments: ["locale"],
    layer: "demo",
  },  
  {
    id: "demo-live-search-source",
    pattern: "/[locale]/demo/live-search-source",
    example: "/en/demo/live-search-source",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-seo-baseline",
    pattern: "/[locale]/demo/seo-baseline",
    example: "/en/demo/seo-baseline",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-parallel-routes",
    pattern: "/[locale]/demo/parallel-routes",
    example: "/en/demo/parallel-routes",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-parallel-routes-with-modal",
    pattern: "/[locale]/demo/parallel-routes/with-modal",
    example: "/en/demo/parallel-routes/with-modal",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-modal-vs-full-page",
    pattern: "/[locale]/demo/modal-vs-full-page",
    example: "/en/demo/modal-vs-full-page",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-suspense-streaming",
    pattern: "/[locale]/demo/suspense-streaming",
    example: "/en/demo/suspense-streaming",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-supabase-architecture",
    pattern: "/[locale]/demo/supabase-architecture",
    example: "/en/demo/supabase-architecture",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-supabase-rls",
    pattern: "/[locale]/demo/supabase-rls",
    example: "/en/demo/supabase-rls",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "login",
    pattern: "/[locale]/login",
    example: "/en/login",
    dynamicSegments: ["locale"],
    layer: "app",
  },
  {
    id: "auth-callback",
    pattern: "/auth/callback",
    example: "/auth/callback?next=/en/favorites",
    dynamicSegments: [],
    layer: "api",
  },
  {
    id: "demo-supabase-auth",
    pattern: "/[locale]/demo/supabase-auth",
    example: "/en/demo/supabase-auth",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-supabase-cloud-favorites",
    pattern: "/[locale]/demo/supabase-cloud-favorites",
    example: "/en/demo/supabase-cloud-favorites",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
  {
    id: "demo-final-architecture",
    pattern: "/[locale]/demo/final-architecture",
    example: "/en/demo/final-architecture",
    dynamicSegments: ["locale"],
    layer: "demo",
  },
];
